version: "3"
services:
  postgres_db:
    image: docker.io/library/postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: python_request/
    command: python3 ./main.py
    container_name: backend
    depends_on:
      - postgres_db
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  reverse-proxy:
    build: nginx_rev_proxy/
    command: nginx -g 'daemon off;'
    ports:
      - 8080:80
    depends_on:
      - postgres_db
      - app

volumes:
  db_data: